### ISSUE TITLE
"timeout" must be a number

### ISSUE THREAD

**Issue by comptechbranden** [atsage/node-red-contrib-mssql-ps#1]
I cant connect to server but see an error for Invalid arguments: "timeout" must be a number. I am using a number and tried another number. There is no spaces. The info screen looks good too. What should I be doing here? Thanks!

**Comment by asage-me** [comment]
What number are you using for the timeout?

**Comment by asage-me** [comment]
Also, is this a browser error or in the node-red log?

**Comment by NetHans** [comment]
I got the same error message.
I solved the problem by changing the source code in line 21 (mssql-ps.js)

Original:
```
[...]
connectionTimeout: this.server.timeout,
[...]
```

Change:
```
[...]
connectionTimeout: parseInt(this.server.timeout),
[...]
```

**Comment by asage-me** [comment]
@comptechbranden @NetHans what version of node.js are you on, and are you on Windows or Linux?

**Comment by asage-me** [comment]
I can't see this causing any problems so I went ahead and made the change.  Pushed to npm.

**Comment by NetHans** [comment]
Sorry for the late reply. I still use NodeJs in version 6.9.1
