### ISSUE TITLE
Parameter type in msg.params definition

### ISSUE THREAD

**Issue by tmdoit-zz** [atsage/node-red-contrib-mssql-ps#4]
Why not send parameter type in msg.params? like:
```
msg.params = {
    id: {
        value: 1,
        type: "INT"
    },
    name: {
        value: "John Doe",
        type: "VARCHAR"
    }
}
```
or
```
msg.params = {
    id: [1, "INT"],
    name: ["John Doe", "VARCHAR"]
}
```

**Comment by asage-me** [comment]
I'm not sure what this would accomplish as the data types will be defined in the table.  What is the use case?

**Comment by tmdoit-zz** [comment]
Because I have to define parameters outside of node, why split definition places into two places - one for values and one for types?

**Comment by asage-me** [comment]
I just don't see the benefit in this, and it allows a node before it to determine what the type is.  I won't be adding this request.

**Comment by tmdoit-zz** [comment]
So I don't understand something, what's the purpose of the 'Parameters' box in node? When I need to use it (add parameters)?

**Comment by asage-me** [comment]
Parameters are the values you are passing to the prepared statement.  https://i.imgur.com/bm9JH4p.png
